# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            x61 x69
tagline:          Artificial Ignorance
url:              http://x61x69.fredzhao.com
paginate:         1
baseurl:          /x61x69
author:
  name:           Fred Zhao

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
